name: SpringBoot_GitHubAction_SonarQube_DockerHub
on:
 push:
  branches: ["main","dev"]
 workflow_dispatch:
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2
      with:
          fetch-depth: 0

    - name: Setup JDK 21
      uses: actions/setup-java@v4.7.0
      with:
        java-version: 21
        distribution: "temurin"
        cache: maven
    
    - name: Build maven
      run: mvn clean install -DskipTests=true
      working-directory: SpringBootSonarQube
      
    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=kyawyea92_springboot_GithubAction_SonarQube_DockerHub
      working-directory: SpringBootSonarQube
      
    - name: Check SonarQube Quality Gate
      id: sonar
      run: |
          sleep 10
          STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=kyawyea92_springboot_GithubAction_SonarQube_DockerHub" | jq -r .projectStatus.status)
          echo "SonarQube Quality Gate status: $STATUS"
          if [[ "$STATUS" != "NONE" ]]; then
            echo "Quality gate failed"
            exit 1
          fi
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.0
      with:
       name: springboot_sonarqube
       path: SpringBootSonarQube/target/*.jar
 deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
         name: springboot_sonarqube
         path: ./SpringBootSonarQube/target
        
      - name: Check file list
        run: ls -al SpringBootSonarQube/target

      - name: deploy and push to DockerHub
        run: |
         docker build -t SpringBootSonarQube/ kyayealwin/springboot_sonarqube:v1.0.0 .
         docker login -u kyawyelwin -p ${{secrets.DOCKER_PASSWORD}}
         docker push kyawyelwin/springboot_sonarqube:v1.0.0
