name: SpringBoot_GitHubAction_SonarQube_DockerHub
on:
 push:
  branches: ["main","dev"]
 workflow_dispatch:
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2
      with:
          fetch-depth: 0

    - name: Java Setup 21
      uses: actions/setup-java@v4.7.0
      with:
       java-version: 21
       distribution: 'zulu'
    
    - name: Build maven
      run: clean maven package
      
    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build and analyze
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=kyawyea92_springboot_GithubAction_SonarQube_DockerHub
    
    - name: Check SonarQube Quality Gate
      id: sonar
      run: |
          sleep 10
          STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "https://sonarcloud.io/api/qualitygates/project_status?projectKey=kyawyea92_springboot_GithubAction_SonarQube_DockerHub" | jq -r .projectStatus.status)
          echo "SonarQube Quality Gate status: $STATUS"
          if [[ "$STATUS" != "OK" ]]; then
            echo "Quality gate failed"
            exit 1
          fi
 deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
  
      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build and Push Docker Image
        run: |
            docker build -t kyawyelwin/springboot_sonarqube:latest .
            docker push kyawyelwin/springboot_sonarqube:latest
